name: Node.js CI

on:
  push:
    branches: [ ch-Setup-Continuous-Integration-and-Quality-Assurance-pipeline ]
  pull_request:
    branches: [ ch-Setup-Continuous-Integration-and-Quality-Assurance-pipeline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.3
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
